# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Contentful Jekyll Single Space Example
email: david.litvak@contentful.com
description: > # this means to ignore newlines until "baseurl:"
  Single Space Example using Jekyll and Contentful
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: contentfulapp
github_username:  dlitvakb

  # Build settings
markdown: kramdown

contentful:
  spaces:
    - links:
        space: ylid7ivby73q
        access_token: 2fb15d2dc086546ad616b36b78c466b9aa2731d7644d54f9659da260276de619
